# Generated by Django 2.0.6 on 2019-07-16 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('salary', models.FloatField()),
                ('age', models.SmallIntegerField()),
                ('headpic', models.ImageField(null=True, upload_to='pics')),
            ],
        ),
    ]
